// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaUMhV0uLKCvqQlz9ZVNQjoKG5fbP4dqM',
    appId: '1:368779658247:web:9fb68f994c0ce54ac156a2',
    messagingSenderId: '368779658247',
    projectId: 'molodost-mololearn',
    authDomain: 'molodost-mololearn.firebaseapp.com',
    storageBucket: 'molodost-mololearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRVI5Y7Zzsq929IU4Q2XaQpT2e1qGGASw',
    appId: '1:368779658247:android:afbd6b85eec22efbc156a2',
    messagingSenderId: '368779658247',
    projectId: 'molodost-mololearn',
    storageBucket: 'molodost-mololearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSnWFOLtIoJADoAFXzusEeV5eL-TOF3s',
    appId: '1:368779658247:ios:af49d66eca6af67cc156a2',
    messagingSenderId: '368779658247',
    projectId: 'molodost-mololearn',
    storageBucket: 'molodost-mololearn.firebasestorage.app',
    iosClientId: '368779658247-vrav6knt5951jivfsmsn90tnhctq920a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mololearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSnWFOLtIoJADoAFXzusEeV5eL-TOF3s',
    appId: '1:368779658247:ios:af49d66eca6af67cc156a2',
    messagingSenderId: '368779658247',
    projectId: 'molodost-mololearn',
    storageBucket: 'molodost-mololearn.firebasestorage.app',
    iosClientId: '368779658247-vrav6knt5951jivfsmsn90tnhctq920a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mololearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaUMhV0uLKCvqQlz9ZVNQjoKG5fbP4dqM',
    appId: '1:368779658247:web:d55975580f8a2167c156a2',
    messagingSenderId: '368779658247',
    projectId: 'molodost-mololearn',
    authDomain: 'molodost-mololearn.firebaseapp.com',
    storageBucket: 'molodost-mololearn.firebasestorage.app',
  );

}